language: node_js
node_js:
  - "16"
dist: trusty
services:
  - redis-server
  - mongodb
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
    - node_modules
    - client/node_modules
before_install:
  - mongo --version
install:
  - npm install
  - npm run build

script:
  - nohup npm run start &
  - sleep 30
  - npm run test
